config/routes.rb
Torti::Application.routes.draw do

  get "pie/genPie"

  get "set_language/english"

  get "set_language/german"

  scope "(:locale)", :locale => /en|de/ do
    root :to => 'login#login'
    get "login/login"
  end

    scope "(:locale)", :locale => /en|de/ do
    root :to => 'login#default'
    get "login/default"
  end

  get "login/login"
  post "login/login"
  get "login/logout"
  post "login/logout"
  get "login/default"

  resources :answers

  resources :statistics, :only => [:index]

  resources :students #, :only => [:new, :create, :index]

  get 'students/:id/validate' => 'students#validate' , :as => "validate"

  resources :registerd_users

end

app/models/registerd_user.rb
class RegisterdUser < ActiveRecord::Base
  attr_accessible :email, :id, :password, :registerdSince, :type
  has_one :statistic
  
end

app/controllers/registerd_users_controller.rb
class RegisterdUsersController < ApplicationController
  # GET /registerd_users
  # GET /registerd_users.json
  def index
    @registerd_users = RegisterdUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @registerd_users }
    end
  end

  # GET /registerd_users/1
  # GET /registerd_users/1.json
  def show
    @registerd_user = RegisterdUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @registerd_user }
    end
  end

  # GET /registerd_users/new
  # GET /registerd_users/new.json
  def new
    @registerd_user = RegisterdUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @registerd_user }
    end
  end

  # GET /registerd_users/1/edit
  def edit
    @registerd_user = RegisterdUser.find(params[:id])
  end

  # POST /registerd_users
  # POST /registerd_users.json
  def create
    @registerd_user = RegisterdUser.new(params[:registerd_user])

    respond_to do |format|
      if @registerd_user.save
        format.html { redirect_to @registerd_user, notice: 'Registerd user was successfully created.' }
        format.json { render json: @registerd_user, status: :created, location: @registerd_user }
      else
        format.html { render action: "new" }
        format.json { render json: @registerd_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /registerd_users/1
  # PUT /registerd_users/1.json
  def update
    @registerd_user = RegisterdUser.find(params[:id])

    respond_to do |format|
      if @registerd_user.update_attributes(params[:registerd_user])
        format.html { redirect_to @registerd_user, notice: 'Registerd user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @registerd_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registerd_users/1
  # DELETE /registerd_users/1.json
  def destroy
    @registerd_user = RegisterdUser.find(params[:id])
    @registerd_user.destroy

    respond_to do |format|
      format.html { redirect_to registerd_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/registerd_users_helper.rb
module RegisterdUsersHelper
end

app/views/registerd_users/_form.html.erb
<%= form_for(@registerd_user) do |f| %>
  <% if @registerd_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@registerd_user.errors.count, "error") %> prohibited this registerd_user from being saved:</h2>

      <ul>
      <% @registerd_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.number_field :password %>
  </div>
  <div class="field">
    <%= f.label :registerdSince %><br />
    <%= f.datetime_select :registerdSince %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registerd_users/edit.html.erb
<h1>Editing registerd_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @registerd_user %> |
<%= link_to 'Back', registerd_users_path %>

app/views/registerd_users/index.html.erb
<h1>Listing registerd_users</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Email</th>
    <th>Password</th>
    <th>Registerdsince</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @registerd_users.each do |registerd_user| %>
  <tr>
    <td><%= registerd_user.id %></td>
    <td><%= registerd_user.email %></td>
    <td><%= registerd_user.password %></td>
    <td><%= registerd_user.registerdSince %></td>
    <td><%= registerd_user.type %></td>
    <%# <td><%= link_to 'Show', registerd_user </td> %>
    <td><%= link_to 'Edit', edit_registerd_user_path(registerd_user) %></td>
    <%# <td><%= link_to 'Destroy', registerd_user, method: :delete, data: { confirm: 'Are you sure?' } </td> %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Registerd user', new_registerd_user_path %>

app/views/registerd_users/new.html.erb
<h1>New registerd_user</h1>

<%= render 'form' %>

<%= link_to 'Back', registerd_users_path %>

app/views/registerd_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @registerd_user.id %>
</p>

<p>
  <b>Email:</b>
  <%= @registerd_user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @registerd_user.password %>
</p>

<p>
  <b>Registerdsince:</b>
  <%= @registerd_user.registerdSince %>
</p>

<p>
  <b>Type:</b>
  <%= @registerd_user.type %>
</p>


<%= link_to 'Edit', edit_registerd_user_path(@registerd_user) %> |
<%= link_to 'Back', registerd_users_path %>