config/routes.rb
Torti::Application.routes.draw do

  get "pie/genPie"

  get "set_language/english"

  get "set_language/german"

  scope "(:locale)", :locale => /en|de/ do
    root :to => 'login#login'
    get "login/login"
  end

    scope "(:locale)", :locale => /en|de/ do
    root :to => 'login#default'
    get "login/default"
  end

  get "login/login"
  post "login/login"
  get "login/logout"
  post "login/logout"
  get "login/default"

  resources :answers

  resources :statistics, :only => [:index]

  resources :students #, :only => [:new, :create, :index]

  get 'students/:id/validate' => 'students#validate' , :as => "validate"

  resources :registerd_users

end

app/controllers/login_controller.rb
require 'digest/md5'

class LoginController < ApplicationController

  before_filter :set_locale

  private
  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  public
  def login
    @error = ""
    if(params[:username] != nil)
      @user = RegisterdUser.find_by_email(params[:username])
      if(@user == nil || @user.nil? || @user == nil.class)
        @error = "No User with "+params[:username]+" found."
      else
        if(@user.registerdSince.to_i < 1)
          @error = "User needs to validate his E-mail first."
        elsif params[:password] != nil && @user.password == Digest::MD5.hexdigest(params[:password]).to_s
          session[:userId] = @user.id
          if(session[:beforeLogin] == nil)
            redirect_to(:action => 'default')
          else
            redirect_to(session[:beforeLogin])
          end
        else
          @error = "Can find user but passwords not equal."
       end
      end
    end
  end

  def default
    @user = getUser(:login_default);
  end

  def logout
     session.delete(:userId)
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/default.html.erb
<h1>Main Page</h1>
<p>Find me in app/views/login/default.html.erb</p>

<%if session[:user] != nil %>
-=<%= session[:user].email %>=-
<%end %>

<%if @user.is_a?(Student) %>
<!-- Student stuff here -->
<%= link_to 'Statistic', statistics_path %>
<%else %>
<!-- do dozent stuff here -->

<%end %><br />

<p><b>I18n.locale:</b>
<%= I18n.locale %>
</p>
<%= link_to 'Logout', login_logout_path %>

app/views/login/login.html.erb
<h1>Login</h1>
<p>
<%= link_to_unless I18n.locale == :en, "English", set_language_english_path %>
|
<%= link_to_unless I18n.locale == :de, "Deutsch", set_language_german_path %>
</p>
<%=t ('.You_have_to_login_now') %><br />
<%=@error %><br />
<form action="" method="get" ><!-- bug in ruby mit post http://www.arailsdemo.com/posts/44 -->
	<table>
		<tr>
			<td><%=t ('.email') %>:</td><td><input name="username" /></ td>
		</ tr>
		<tr>
			<td><%=t ('.password') %>:</td><td><input type="password" name="password" /></td>
		</ tr>
		<tr>
			<td><input type="hidden" name="goto" value="<%=session[:beforeLogin]%>"></td><td><input type="submit" value="<%=t ('.login') %>"/></td>
		</ tr>
	</ table>
</form>
<%= link_to 'Register', new_student_path %>

app/views/login/logout.html.erb
<h1>Logout</h1>
Ende
<%= link_to 'Default', login_default_path %>